### PR TITLE
jasmine matches and protractor updates

### PR DESCRIPTION
**Pull request by AlexanderTunick**
updated jasmine matches to 2.0.0 version and protractor to 5.2.0 version

### CODE REVIEW

**Comment by AlexanderTunick** [comment]
@Xotabu4 
I cloned brand new project again, made changes in a new branch (update jasmine matches and protractor only, reinstalled node_modules and added matches into Protractor.config file and homepage file), that's it.

But CI still doesn't let me pass further 

I don't know what to do else, really, I would like to do it better, but perhaps doing something wrong

**Review by Xotabu4 — CHANGES_REQUESTED** [review]
- 26 files in PR, remove idea files
- Do not add compiled .js files to generator template
- importing of jasmine matchers are still wrong
- package.lock files not needed in templates and generator (for now)
- no need to update homepage.spec.ts
- do not modify generator root package.json file

**Comment by AlexanderTunick** [comment]
26 files in PR, remove idea files - removed again and added to git ignore
Do not add compiled .js files to generator template - didn't compile 
importing of jasmine matchers are still wrong - fixed 
package.lock files not needed in templates and generator (for now) - deleted
no need to update homepage.spec.ts - gave changes back 
do not modify generator root package.json file - gave changes back (left only version number)

**Comment by Xotabu4** [comment]
@Alextunchii please see files in this pull request - compiled files are still here

**Pull request closed without merging**
